import React, { createContext, useState, useContext, useEffect } from "react";

export const releaseNotes = {
  es: [
    {
      version: "v1.0.5",
      changes: [
        "Nuevo diseño UI/UX totalmente renovado",
        "Herramientas JDK y Platform Tools integradas nativamente",
        "Mejoras y optimización en métodos y comandos ADB",
        "Nuevas inspecciones en el APK con detección de librerías utilizadas y más",
        "Suite de simuladores unificada en un solo punto",
        "Simuladores de integración: Simulador SDK, protocolo simplificado y conexión por puertos COM",
      ],
    },
    {
      version: "v1.0.3",
      changes: [
        "Carpeta en el proceso de firma y guardado de directorio",
        "Soporte de Jarsigner para APKs sin firma o con firma existente",
        "Mejoras visuales y nuevo ícono de la aplicación",
        "Instalación de APK mejorada: barra de progreso y gestión del error -1",
        "Experiencia de instalación más profesional y detallada",
      ],
    },
    {
      version: "v1.0.1",
      changes: [
        "Nueva interfaz moderna desarrollada en Flutter",
        "Mejoras críticas en estabilidad y rendimiento",
        "Optimización de conexión ADB",
        "Refactorización completa del motor de análisis de APK",
        "La consola CMD ya no se muestra al ejecutar herramientas",
      ],
    },
  ],

  en: [
    {
      version: "v1.0.5",
      changes: [
        "Brand new UI/UX design experience",
        "Natively integrated JDK and Platform Tools",
        "Improvements and optimization in ADB methods and commands",
        "New APK inspections including used libraries detection and extra insights",
        "Unified simulator suite all in one place",
        "Integration simulators: SDK simulator, simplified protocol, and COM port connection",
      ],
    },
    {
      version: "v1.0.3",
      changes: [
        "Folder selection in signing process and directory saving",
        "Jarsigner support for unsigned or already-signed APKs",
        "Visual improvements and new app icon",
        "Improved APK installation: progress bar and error -1 handling",
        "More professional and detailed installation experience",
      ],
    },
    {
      version: "v1.0.1",
      changes: [
        "New modern interface developed in Flutter",
        "Critical stability and performance improvements",
        "ADB connection optimization",
        "Complete refactoring of the APK analysis engine",
        "CMD console no longer appears when running tools",
      ],
    },
  ],

  pt: [
    {
      version: "v1.0.5",
      changes: [
        "Novo design de UI/UX totalmente renovado",
        "Ferramentas JDK e Platform Tools integradas nativamente",
        "Melhorias e otimizações nos métodos e comandos ADB",
        "Novas inspeções no APK com detecção de bibliotecas utilizadas e mais",
        "Suite de simuladores unificada em um único ponto",
        "Simuladores de integração: Simulador SDK, protocolo simplificado e conexão por portas COM",
      ],
    },
    {
      version: "v1.0.3",
      changes: [
        "Pasta no processo de assinatura e salvamento de diretório",
        "Suporte a Jarsigner para APKs sem assinatura ou com assinatura existente",
        "Melhorias visuais e novo ícone do aplicativo",
        "Instalação de APK aprimorada: barra de progresso e tratamento do erro -1",
        "Experiência de instalação mais profissional e detalhada",
      ],
    },
    {
      version: "v1.0.1",
      changes: [
        "Nova interface moderna desenvolvida em Flutter",
        "Melhorias críticas de estabilidade e desempenho",
        "Otimização da conexão ADB",
        "Refatoração completa do mecanismo de análise de APK",
        "O console CMD não aparece mais ao executar ferramentas",
      ],
    },
  ],
};

const translations = {
  es: {
    // Header
    features: "Características",
    download: "Descargar",
    github: "GitHub",
    language: "Idioma",
    theme: "Tema",

    "topbar.home": "Inicio",
    "topbar.features": "Características",
    "topbar.download": "Descargar",
    "topbar.github": "GitHub",
    "topbar.logoText": "ISV Toolkit",
    "topbar.language": "Idioma",
    "topbar.theme": "Tema",
    "topbar.diagramacion": "Diagramación",

    // Hero Section
    heroTitle: "ISV Toolkit",
    heroDescription:
      "Herramientas especializadas para desarrolladores Android y QA. Optimiza tu flujo de diferentes actividades de análisis en una sola plataforma.",
    feature1: "Sencillo",
    feature1Desc: "No necesitas escribir comandos y mover archivos manualmente",
    feature2: "Información",
    feature2Desc: "Toda la información de un APK con solo inspeccionarla",
    feature3: "Integrado",
    feature3Desc: "Múltiples herramientas integradas en una sola plataforma",
    feature4: "Firma JKS",
    feature4Desc: "Puedes generar o firmar APKs con claves JKS",

    // About Section
    aboutTitle: "¿Qué es ISV Toolkit?",
    aboutDescription:
      "Una plataforma integral para desarrolladores ISV con herramientas especializadas en pruebas, optimización y desarrollo de software.",
    purposeTitle: "Propósito Principal",
    purposeDesc:
      "Simplificar el desarrollo y testing de aplicaciones ISV con herramientas especializadas.",
    toolsTitle: "Herramientas Integradas",
    toolsDesc:
      "Suite completa para testing, optimización de rendimiento y análisis de código.",
    benefitsTitle: "Beneficios Clave",
    benefitsDesc:
      "Reducción de tiempo de desarrollo y mejores prácticas implementadas.",

    // Image Sections
    analysisTitle: "Análisis Completo de APKs",
    analysisDesc:
      "Inspecciona cualquier archivo APK y obtén información detallada sobre permisos, actividades, servicios, proveedores y más. Todo en una interfaz intuitiva sin necesidad de comandos complejos.",
    analysis1: "Extracción de metadatos del APK",
    analysis2: "Información de esquema de firma y Hash",
    analysis3: "Tamaño y formato del APK",
    analysis4: "Permisos sensibles y norma de seguridad",

    signingTitle: "Firma y Verificación de APKs",
    signingDesc:
      "Firma tus aplicaciones con claves JKS personalizadas o verifica la firma de APKs existentes. Genera nuevas claves y mantén un control completo sobre el proceso de firma.",
    signing1: "Firma de APKs con claves JKS",
    signing2: "Generación de nuevas claves de firma",
    signing3: "Verificación de firmas existentes",
    signing4: "Alineación y optimización de APKs",

    logcatTitle: "Logcat Experiences",
    logcatDesc:
      "Accede a los registros de logcat de forma intuitiva y eficiente. Visualiza, filtra y exporta los registros de manera sencilla.",
    logcat1: "Visualización de registros de logcat",
    logcat2: "Filtrado de registros por niveles de log",
    logcat3: "Exportación de registros a archivos",
    logcat4: "Guarda y exportar el registro",

    adbTitle: "Comandos Avanzados ADB",
    adbDesc:
      "Ejecuta comandos ADB complejos a través de una interfaz gráfica intuitiva. Automatiza tareas repetitivas y accede a funciones avanzadas sin necesidad de memorizar comandos.",
    adb1: "Interfaz gráfica para comandos ADB",
    adb2: "Scripts predefinidos para tareas comunes",
    adb3: "Ejecución de comandos personalizados",
    adb4: "Historial de comandos ejecutados",



    managementTitle: "Configuraciones Globales",
    managementDesc:
      "Personaliza tu experiencia en ISV Toolkit. Cambia el idioma, ajusta el tema visual y gestiona el estado de tu terminal conectada de forma remota.",
    management1: "Idiomas: Español, Inglés y Portugués",
    management2: "Modo Oscuro y Claro",
    management3: "Reboot remoto del terminal",
    management4: "Persistencia de preferencias",

    integrationSimTitle: "Simuladores de Integración",
    integrationSimDesc:
      "Suite completa de simuladores diseñada para integradores. Prueba y valida la comunicación mediante simulador SDK, protocolo simplificado y conexión por puertos COM.",
    integrationSim1: "Simulador SDK y entorno de pruebas",
    integrationSim2: "Soporte para protocolo simplificado",
    integrationSim3: "Conexión e inspección por puertos COM (Serie/USB)",
    integrationSim4: "Validación de comunicación en tiempo real para integradores",

    // Download Section
    downloadTitle: "Descarga ISV Toolkit",
    downloadSubtitle:
      "Disponible para Windows",
    windows: "Windows",
    version: "Versión:",
    file: "Archivo:",
    size: "Tamaño:",
    requirements: "Requisitos:",
    downloadButton: "Descargar para",
    requirementsTitle: "Requisitos del Sistema",
    dependenciesTitle: "Dependencias Necesarias",
    os: "Sistema Operativo",
    osDesc: "Windows 7/8/10/11 (64-bit)",
    ram: "Memoria RAM",
    ramDesc: "Mínimo 2GB, recomendado 4GB",
    disk: "Espacio en Disco",
    diskDesc: "500MB mínimo, 1GB recomendado",
    internet: "Conexión a Internet",
    internetDesc: "Para descargar dependencias y actualizaciones",
    platformTools: "Platform Tools",
    platformToolsDesc: "ADB y Fastboot esenciales",
    buildTools: "Build Tools",
    buildToolsDesc: "AAPT, APKSigner, etc.",
    jdk: "JDK 11",
    jdkDesc: "Para JarSigner",
    downloading: "Descargando...",
    learnMore: "Saber más",
    
    // Simulator
    simulatorTitle: "Simulador Cloud to Cloud",
    simulatorDesc: "Consola de comandos C2C. Valida tokens y examina el log de eventos.",
    backToMain: "Volver al inicio",
    simSendBtn: "Enviar Comando",
    simAtendido: "Atendido",
    simDesatendido: "Desatendido",
    countryChile: "🇨🇱 Chile",
    countryArgentina: "🇦🇷 Argentina",
    simCountrySelectLabel: "SELECCIONAR PAÍS",
    simEnv: "ENTORNO",
    simCommand: "COMANDO",
    simParams: "PARÁMETROS",
    simHistory: "HISTORIAL",
    simFullHistory: "Ver historial completo",
    simTransactions: "transacciones",
    simTransaction: "transacción",
    simShowing: "Mostrando",
    simOf: "de",
    simPerPage: "Por pág:",
    simSearchPlaceholder: "Buscar por endpoint, estado (200, 400), método...",
    simNoHistory: "Sin historial",
    confirmClearHistoryTitle: "Borrar Historial",
    confirmClearHistoryHeading: "¿Vaciar el historial de transacciones?",
    confirmClearHistoryDesc: "Esta acción eliminará permanentemente todas las transacciones guardadas en el almacenamiento local. No se podrá deshacer.",
    confirmClear: "Sí, vaciar historial",
    cancel: "Cancelar",
    simTriadWarn: "Faltan campos de la tríada (ID Terminal, ID Sucursal o Serial Number). ¿Ejecutar el comando de todas formas?",
    simTokenActive: "Bearer Token Activo",
    simNoToken: "Sin Token — abrir configuración",
    simAuthBtn: "Generar Auth Token",
    simClearBtn: "Limpiar",
    simProdEnv: "PRODUCCIÓN",
    simParamsCount: "parámetros",
    simWaiting: "Esperando petición...",
    tokenSaved: "Token Guardado",
    unauthorizedTitle: "Acceso Denegado (401)",
    unauthorizedDesc: "El Simulator recibió un error 401. El token podría estar vencido o no configurado. ¿Generar uno nuevo?",
    ignoreBtn: "Ignorar",
    tokenConfigTitle: "Configuración Token",
    terminalCreds: "Credenciales de Terminal",
    tokenStatus: "Estado del Token",
    tokenActive: "TOKEN ACTIVO",
    tokenMissing: "SIN TOKEN",
    tokenInfo: "Se enviará como Authorization: Bearer en cada request.",
    tokenGuide: "Ingresá tus credenciales y presioná el botón obtener.",
    tokenConfigBtn: "Configuración Token",
    clientIdLabel: "CLIENT ID",
    clientSecretLabel: "CLIENT SECRET",
    fetchTokenBtn: "Obtener Token",
    fetchingToken: "Obteniendo...",
    copy: "Copiar",
    copied: "Copiado!",
    
    // Commands
    "cmd.poll": "Conexión",
    "cmd.validate_ar": "Validar comunicación",
    "cmd.params_ar": "Información de terminal",
    "cmd.sale_ar": "Venta",
    "cmd.return_ar": "Devolución",
    "cmd.lastvoucher_ar": "Reimprimir",
    "cmd.details_ar": "Detalle de Venta",
    "cmd.totals_ar": "Totales",
    "cmd.c2c_sale": "Venta",
    "cmd.sale_promo": "Venta Promo",
    "cmd.refund": "Anulación",
    "cmd.close": "Cierre",
    "cmd.details": "Detalles",
    "cmd.return": "Devolución",
    "cmd.duplicate": "Duplicado",
    "cmd.bioauth": "Bio Auth",
    "cmd.print": "Imprimir",
    "cmd.c2c_mode": "Modo C2C",
    "cmd.flash_sale": "Venta Flash",

    // Fields
    "field.idTerminal": "ID Terminal",
    "field.idSucursal": "ID Sucursal",
    "field.serialNumber": "Serial Number",
    "field.amount": "Monto ($)",
    "field.ticketNumber": "Ticket #",
    "field.customId": "Custom ID",
    "field.idPromo": "ID Promo",
    "field.operationId": "N° de Comprobante",
    "field.authCode": "Cód. Autorización",
    "field.installments": "Cuotas",
    "field.printOnPos": "Imprimir en POS",
    "field.c2cMode": "Modo Atendido/Desatendido",
    "field.rutToValidate": "RUT a Validar",
    "field.authType": "Tipo Auth",
    "field.tip": "Propina",
    "field.saleType": "Tipo Venta",
    "field.paymentCategory": "Categoría de Pago",
    "paymentCategory.none": "Ninguna",
    "field.employeeId": "ID Empleado",
    "field.flashCount": "Cantidad de Ventas",
    "field.flashAltThreshold": "Cambiar monto desde venta #",
    "field.flashBaseAmount": "Monto Base ($)",
    "field.flashAltAmount": "Monto Alternativo ($)",
    "field.amountStatic": "Monto Fijo",
    "field.ticketStatic": "Ticket Fijo",
    "triad.promptName": "Ingrese un nombre para la tríada:",
    "triad.pasteTitle": "Pegado Especial de Tríada",
    "triad.pastePlaceholder": "Pegue aquí los datos de su terminal (separados por tabulador, comas o espacios)...",
    "triad.pasteApply": "Procesar",
    "triad.pasteError": "No se pudo detectar un formato válido de tríada. Asegúrese de incluir ID Terminal, ID Sucursal y Serial Number.",
    "triad.pasteSuccess": "Tríada cargada con éxito",
    "field.planId": "ID Plan",
    "field.interest": "Interés",
    "field.operationMode": "Modo Operación",
    "field.skipConfirmation": "Omitir Confirmación",
    "field.skipReceipt": "Omitir Comprobante",
    "field.originalTransDate": "Fecha Operación Original",
    "field.originalDate": "Fecha Original",
    "field.originalTime": "Hora Original",
    "viewFullHistory": "Ver transacciones restantes ({count})",
    simClearResponse: "Limpiar Response",
    confirmClearToken: "¿Estás seguro de que deseas borrar el Token guardado?",
    simVersionNotice: "Este comando al igual que el de Venta Promo, c2cmode y Bio Auth son solo para las versiones 1.0.X de iOnetech",
    confirmClearHistory: "¿Estás seguro de que deseas borrar el historial de transacciones?", 
    cancelConfirm: "La transacción seguirá por el servicio pero si cancelas no podrás ver la respuesta en esta pantalla.",
    simCancelBtn: "Cancelar",
    simStatus: "Status",
    simRequestBody: "Request Body",
    simResponseData: "Response Data",
    simTransactionDetail: "Detalle de Transacción",
    simCopied: "Copiado al portapapeles",
    simSending: "Enviando...",
    simBackToCommands: "Volver a comandos",
    copyResponse: "Copiar Respuesta",
    clearResponse: "Limpiar Response",
    simTourTooltip: "Iniciar Tour Interactivo",
    copyToken: "Copiar Token",
    copyRequest: "Copiar JSON",
    edit: "Editar",
    delete: "Eliminar",
    simClearHistory: "Limpiar Historial",
    invalidRut: "RUT inválido (Módulo 11)",
    // Onboarding
    "tour.welcome": "¡Bienvenido al Simulador C2C! Aquí podrás probar y validar comandos sin necesidad de Postman.",
    "tour.countrySelector": "Primero, elige el País y el Entorno (DEV, UAT) en el que quieres operar. Esto ajustará la URL de la API automáticamente.",
    "tour.authBtn": "Configura tus credenciales y obtén tu Token. Es esencial para poder autorizar las transacciones.",
    "tour.requestResponse": "Aquí verás el cuerpo de tu petición (JSON) y la respuesta exacta del servidor.",
    "tour.sendBtn": "¡Una vez configurado todo, presiona aquí para enviar el comando!",
    "tour.commandSelector": "Despliega este menú para seleccionar el tipo de operación: Venta, Anulación, Batch, etc.",
    "tour.triads": "Para no escribir siempre los mismos datos, puedes guardar tus combinaciones frecuentes de Terminal, Sucursal y Serial Number (Triadas).",
    "tour.params": "¡Ojo con estos campos! Aquí definirás exactamente los parámetros dinámicos que vas a enviar en el cuerpo (body) de tu petición al POS (monto, número de ticket, etc).",
    "tour.history": "Todas tus operaciones recientes quedarán registradas en este historial para que puedas revisarlas detalladamente.",
    // Triads
    "triad.requiredFields": "ID Terminal, ID Sucursal y Serial Number son requeridos",
    "triad.nameRequired": "El nombre es requerido",
    "triad.terminalRequired": "ID Terminal es requerido",
    "triad.sucursalRequired": "ID Sucursal es requerido",
    "triad.serialRequired": "Serial Number es requerido",
    "triad.maxLength": "Los campos no deben exceder 20 caracteres",
    "triad.exists": "Triada ya existe. Seleccionada.",
    "triad.created": "Triada creada",
    "triad.confirmDelete": "¿Eliminar triada \"{name}\"?",
    "triad.duplicate": "La triada modificada coincide con otra existente",
    "triad.saved": "Triada guardada",
    "triad.title": "Triadas Guardadas",
    "triad.createBtn": "CREAR TRIADA",
    "triad.noTriads": "No hay triadas guardadas",
    "triad.createTitle": "Crear Triada",
    "triad.editTitle": "Editar Triada",
    "triad.nameLabel": "Nombre",
    "triad.cancelBtn": "Cancelar",
    "triad.createAction": "Crear",
    "triad.saveAction": "Guardar Triada",
    // Token Modal / Fetching
    "token.envDev": "DEV - Ambiente Desarrollo",
    "token.envUat": "UAT - Ambiente Pruebas",
    "token.privacyNote": "Tus credenciales se procesan de forma segura y se almacenan únicamente de manera local.",
    "token.closeModal": "Cerrar modal",
    simTokenRequired: "Se requiere obtener un token primero",
    errorInvalidAmount: "❌ Error: El monto es inválido",
    errorTicketRequired: "❌ Error: El número de ticket es requerido",
    requestCancelled: "🚫 Petición cancelada",
    flashSaleStarting: "⚡ Iniciando modo Venta Flash...",
    flashSaleStopping: "⏹️ Deteniendo Venta Flash...",
    envLabel: "Entorno",
    templateLoaded: "Plantilla cargada",
  },

  en: {
    // Header
    features: "Features",
    download: "Download",
    github: "GitHub",
    language: "Language",
    theme: "Theme",

    "topbar.home": "Home",
    "topbar.features": "Features",
    "topbar.download": "Download",
    "topbar.github": "GitHub",
    "topbar.logoText": "ISV Toolkit",
    "topbar.language": "Language",
    "topbar.theme": "Theme",
    "topbar.diagramacion": "Diagramming",

    // Hero Section
    heroTitle: "ISV Toolkit",
    heroDescription:
      "Specialized tools for Android developers and QA. Optimize your workflow of different analysis activities in a single platform.",
    feature1: "Simple",
    feature1Desc: "No need to write commands and move files manually",
    feature2: "Information",
    feature2Desc: "All information of an APK by just inspecting it",
    feature3: "Integrated",
    feature3Desc: "Multiple tools integrated into a single platform",
    feature4: "JKS Signing",
    feature4Desc: "You can generate or sign APKs with JKS keys",

    // About Section
    aboutTitle: "What is ISV Toolkit?",
    aboutDescription:
      "A comprehensive platform for ISV developers with specialized tools for testing, optimization and software development.",
    purposeTitle: "Main Purpose",
    purposeDesc:
      "Simplify development and testing of ISV applications with specialized tools.",
    toolsTitle: "Integrated Tools",
    toolsDesc:
      "Complete suite for testing, performance optimization and code analysis.",
    benefitsTitle: "Key Benefits",
    benefitsDesc: "Reduced development time and implemented best practices.",

    // Image Sections
    analysisTitle: "Complete APK Analysis",
    analysisDesc:
      "Inspect any APK file and get detailed information about permissions, activities, services, providers and more. All in an intuitive interface without complex commands.",
    analysis1: "Extraction of APK metadata",
    analysis2: "Signature scheme and Hash information",
    analysis3: "APK size and format",
    analysis4: "Sensitive permissions and security standards",

    signingTitle: "APK Signing and Verification",
    signingDesc:
      "Sign your applications with custom JKS keys or verify signatures of existing APKs. Generate new keys and maintain full control over the signing process.",
    signing1: "APK signing with JKS keys",
    signing2: "Generation of new signing keys",
    signing3: "Verification of existing signatures",
    signing4: "APK alignment and optimization",

    logcatTitle: "Logcat Experiences",
    logcatDesc:
      "Access logcat records intuitively and efficiently. View, filter and export logs easily.",
    logcat1: "Logcat records visualization",
    logcat2: "Log filtering by log levels",
    logcat3: "Export of records to files",
    logcat4: "Save and export the record",

    adbTitle: "Advanced ADB Commands",
    adbDesc:
      "Execute complex ADB commands through an intuitive graphical interface. Automate repetitive tasks and access advanced functions without memorizing commands.",
    adb1: "Graphical interface for ADB commands",
    adb2: "Predefined scripts for common tasks",
    adb3: "Execution of custom commands",
    adb4: "History of executed commands",

    screenTitle: "Screen Recording and Capture",
    screenDesc:
      "Record your Android device screen and capture images in high quality. Perfect for creating tutorials, documenting bugs or sharing demos.",
    screen1: "High quality screen recording",
    screen2: "Instant screenshots",
    screen3: "Resolution and fps configuration",
    screen4: "Multiple export formats",

    managementTitle: "Global Settings",
    managementDesc:
      "Customize your ISV Toolkit experience. Change the language, adjust the visual theme, and manage the status of your connected terminal remotely.",
    management1: "Languages: Spanish, English, and Portuguese",
    management2: "Dark and Light Mode",
    management3: "Remote terminal reboot",
    management4: "Preference persistence",

    integrationSimTitle: "Integration Simulators",
    integrationSimDesc:
      "Complete simulator suite designed for integrators. Test and validate communication using SDK simulator, simplified protocol, and COM port connection.",
    integrationSim1: "SDK Simulator and testing environment",
    integrationSim2: "Support for simplified protocol",
    integrationSim3: "COM port connection and inspection (Serial/USB)",
    integrationSim4: "Real-time communication validation for integrators",

    // Download Section
    downloadTitle: "Download ISV Toolkit",
    downloadSubtitle:
      "Available for Windows",
    windows: "Windows",
    version: "Version:",
    file: "File:",
    size: "Size:",
    requirements: "Requirements:",
    downloadButton: "Download for",
    requirementsTitle: "System Requirements",
    dependenciesTitle: "Required Dependencies",
    os: "Operating System",
    osDesc: "Windows 7/8/10/11 (64-bit)",
    ram: "RAM Memory",
    ramDesc: "Minimum 4GB, recommended 8GB",
    disk: "Disk Space",
    diskDesc: "500MB minimum, 1GB recommended",
    internet: "Internet Connection",
    internetDesc: "For downloading dependencies and updates",
    platformTools: "Platform Tools",
    platformToolsDesc: "Essential ADB and Fastboot",
    buildTools: "Build Tools",
    buildToolsDesc: "AAPT, APKSigner, etc.",
    jdk: "JDK 11",
    jdkDesc: "For JarSigner",
    downloading: "Downloading...",
    learnMore: "Learn More",

    // Simulator
    simulatorTitle: "Cloud to Cloud Simulator",
    simulatorDesc: "C2C command console. Validate tokens and examine event logs.",
    backToMain: "Back to main",
    simSendBtn: "Send Request",
    simAtendido: "Attended",
    simDesatendido: "Unattended",
    countryChile: "🇨🇱 Chile",
    countryArgentina: "🇦🇷 Argentina",
    simCountrySelectLabel: "SELECT COUNTRY",
    simEnv: "ENVIRONMENT",
    simCommand: "COMMAND",
    simParams: "PARAMETERS",
    simHistory: "HISTORY",
    simFullHistory: "View full history",
    simTransactions: "transactions",
    simTransaction: "transaction",
    simShowing: "Showing",
    simOf: "of",
    simPerPage: "Per page:",
    simSearchPlaceholder: "Search by endpoint, status (200, 400), method...",
    simNoHistory: "No history",
    confirmClearHistoryTitle: "Clear History",
    confirmClearHistoryHeading: "Clear transaction history?",
    confirmClearHistoryDesc: "This action will permanently delete all transactions saved in local storage. This cannot be undone.",
    confirmClear: "Yes, clear history",
    cancel: "Cancel",
    simTriadWarn: "Triad details missing (Terminal ID, Branch ID or Serial Number). Execute command anyway?",
    simTokenActive: "Active Bearer Token",
    simNoToken: "No Token — open settings",
    simAuthBtn: "Generate Auth Token",
    simClearBtn: "Clear",
    simProdEnv: "PRODUCTION",
    simParamsCount: "params",
    simWaiting: "Waiting for request...",
    tokenSaved: "Token Saved",
    unauthorizedTitle: "Access Denied (401)",
    unauthorizedDesc: "The Simulator received a 401 error. The token might be expired or not configured. Generate a new one?",
    ignoreBtn: "Ignore",
    tokenConfigTitle: "Token Configuration",
    terminalCreds: "Terminal Credentials",
    tokenStatus: "Token Status",
    tokenActive: "TOKEN ACTIVE",
    tokenMissing: "NO TOKEN",
    tokenInfo: "It will be sent as Authorization: Bearer in every request.",
    tokenGuide: "Enter your credentials and press the fetch button.",
    tokenConfigBtn: "Token Configuration",
    clientIdLabel: "CLIENT ID",
    clientSecretLabel: "CLIENT SECRET",
    fetchTokenBtn: "Get Token",
    fetchingToken: "Fetching...",
    copy: "Copy",
    copied: "Copied!",
    
    // Commands
    "cmd.poll": "Connection",
    "cmd.validate_ar": "Validate Communication",
    "cmd.params_ar": "Terminal Info",
    "cmd.sale_ar": "Sale",
    "cmd.return_ar": "Return",
    "cmd.lastvoucher_ar": "Re-print",
    "cmd.details_ar": "Sale Details",
    "cmd.totals_ar": "Totals",
    "cmd.c2c_sale": "Sale",
    "cmd.sale_promo": "Promo Sale",
    "cmd.refund": "Refund",
    "cmd.close": "Settlement",
    "cmd.details": "Details",
    "cmd.return": "Return",
    "cmd.duplicate": "Duplicate",
    "cmd.bioauth": "Bio Auth",
    "cmd.print": "Print",
    "cmd.c2c_mode": "C2C Mode",
    "cmd.flash_sale": "Flash Sale",

    // Fields
    "field.idTerminal": "Terminal ID",
    "field.idSucursal": "Branch ID",
    "field.serialNumber": "Serial Number",
    "field.amount": "Amount ($)",
    "field.ticketNumber": "Ticket #",
    "field.customId": "Custom ID",
    "field.idPromo": "Promo ID",
    "field.operationId": "Receipt Number",
    "field.authCode": "Auth Code",
    "field.installments": "Installments",
    "field.printOnPos": "Print on POS",
    "field.c2cMode": "Attended/Unattended Mode",
    "field.rutToValidate": "RUT to Validate",
    "field.authType": "Auth Type",
    "field.saleType": "Sale Type",
    "field.paymentCategory": "Payment Category",
    "paymentCategory.none": "None",
    "field.employeeId": "Employee ID",
    "field.flashCount": "Number of Sales",
    "field.flashAltThreshold": "Change amount from sale #",
    "field.flashBaseAmount": "Base Amount ($)",
    "field.flashAltAmount": "Alternative Amount ($)",
    "field.amountStatic": "Fixed Amount",
    "field.ticketStatic": "Fixed Ticket",
    "triad.promptName": "Enter a name for the triad:",
    "triad.pasteTitle": "Special Triad Paste",
    "triad.pastePlaceholder": "Paste your terminal data here (separated by tab, commas, or spaces)...",
    "triad.pasteApply": "Process",
    "triad.pasteError": "Valid triad format could not be detected. Make sure to include Terminal ID, Branch ID and Serial Number.",
    "triad.pasteSuccess": "Triad loaded successfully",
    "viewFullHistory": "View remaining transactions ({count})",
    simClearResponse: "Clear Response",
    confirmClearToken: "Are you sure you want to clear the saved Token?",
    simVersionNotice: "This command as well as Venta Promo, c2c_mode and Bio Auth are only for iOnetech version 1.0.X",
    confirmClearHistory: "Are you sure you want to clear the transaction history?",
    cancelConfirm: "The transaction will continue on the service but if you cancel you won't be able to see the response on this screen.",
    simCancelBtn: "Cancel",
    simStatus: "Status",
    simRequestBody: "Request Body",
    simResponseData: "Response Data",
    simTransactionDetail: "Transaction Detail",
    simCopied: "Copied to clipboard",
    simSending: "Sending...",
    simBackToCommands: "Back to commands",
    copyResponse: "Copy Response",
    clearResponse: "Clear Response",
    simTourTooltip: "Start Interactive Tour",
    copyToken: "Copy Token",
    copyRequest: "Copy Request JSON",
    edit: "Edit",
    delete: "Delete",
    simClearHistory: "Clear History",
    // Onboarding
    "tour.welcome": "Welcome to the C2C Simulator! Here you can test and validate commands without the need for Postman.",
    "tour.countrySelector": "First, choose the Country and Environment (DEV, UAT, PROD) you want to operate in. This will adjust the API URL automatically.",
    "tour.authBtn": "Configure your credentials and get your Token. It is essential for authorizing transactions.",
    "tour.requestResponse": "Here you will see your request body (JSON) and the exact response from the server.",
    "tour.sendBtn": "Once everything is configured, press here to send the command!",
    "tour.commandSelector": "Expand this menu to select the type of operation: Sale, Void, Settlement, etc.",
    "tour.triads": "To avoid writing the same data every time, you can save your frequent combinations of Terminal, Branch, and Serial Number (Triads).",
    "tour.params": "Pay attention to these fields! Here you will define exactly the dynamic parameters you will send in the body of your request to the POS (amount, ticket number, etc).",
    "tour.history": "All your recent operations will be registered in this history so you can review them in detail.",
    // Triads
    "triad.requiredFields": "Terminal ID, Branch ID and Serial Number are required",
    "triad.nameRequired": "Name is required",
    "triad.terminalRequired": "Terminal ID is required",
    "triad.sucursalRequired": "Branch ID is required",
    "triad.serialRequired": "Serial Number is required",
    "triad.maxLength": "Fields must not exceed 20 characters",
    "triad.exists": "Triad already exists. Selected.",
    "triad.created": "Triad created",
    "triad.confirmDelete": "Delete triad \"{name}\"?",
    "triad.duplicate": "The modified triad matches an existing one",
    "triad.saved": "Triad saved",
    "triad.title": "Saved Triads",
    "triad.createBtn": "CREATE TRIAD",
    "triad.noTriads": "No saved triads",
    "triad.createTitle": "Create Triad",
    "triad.editTitle": "Edit Triad",
    "triad.nameLabel": "Name",
    "triad.cancelBtn": "Cancel",
    "triad.createAction": "Create",
    "triad.saveAction": "Save Triad",
    // Token Modal / Fetching
    "token.envDev": "DEV - Development Environment",
    "token.envUat": "UAT - Testing Environment",
    "token.privacyNote": "Your credentials are processed securely and stored only locally.",
    "token.closeModal": "Close modal",
    simTokenRequired: "An access token is required first",
    errorInvalidAmount: "❌ Error: The amount is invalid",
    errorTicketRequired: "❌ Error: Ticket number is required",
    requestCancelled: "🚫 Request cancelled",
    flashSaleStarting: "⚡ Starting Flash Sale mode...",
    flashSaleStopping: "⏹️ Stopping Flash Sale...",
    envLabel: "Environment",
    templateLoaded: "Template loaded",
  },

  pt: {
    // Header
    features: "Características",
    download: "Baixar",
    github: "GitHub",
    language: "Idioma",
    theme: "Tema",

    "topbar.home": "Início",
    "topbar.features": "Características",
    "topbar.download": "Baixar",
    "topbar.github": "GitHub",
    "topbar.logoText": "ISV Toolkit",
    "topbar.language": "Idioma",
    "topbar.theme": "Tema",
    "topbar.diagramacion": "Diagramação",
    // Hero Section
    heroTitle: "ISV Toolkit",
    heroDescription:
      "Ferramentas especializadas para desenvolvedores Android e QA. Otimize seu fluxo de diferentes atividades de análise em uma única plataforma.",
    feature1: "Simples",
    feature1Desc: "Não precisa escrever comandos e mover arquivos manualmente",
    feature2: "Informação",
    feature2Desc: "Toda a informação de um APK apenas inspecionando",
    feature3: "Integrado",
    feature3Desc: "Múltiplas ferramentas integradas em uma única plataforma",
    feature4: "Assinatura JKS",
    feature4Desc: "Você pode gerar ou assinar APKs com chaves JKS",

    // About Section
    aboutTitle: "O que é ISV Toolkit?",
    aboutDescription:
      "Uma plataforma abrangente para desenvolvedores ISV com ferramentas especializadas para testes, otimização e desenvolvimento de software.",
    purposeTitle: "Propósito Principal",
    purposeDesc:
      "Simplificar o desenvolvimento e teste de aplicações ISV com ferramentas especializadas.",
    toolsTitle: "Ferramentas Integradas",
    toolsDesc:
      "Suite completa para testes, otimização de desempenho e análise de código.",
    benefitsTitle: "Benefícios Principais",
    benefitsDesc:
      "Tempo de desenvolvimento reduzido e melhores práticas implementadas.",

    // Image Sections
    analysisTitle: "Análise Completa de APKs",
    analysisDesc:
      "Inspecione qualquer arquivo APK e obtenha informações detalhadas sobre permissões, atividades, serviços, provedores e mais. Tudo em uma interface intuitiva sem comandos complexos.",
    analysis1: "Extração de metadados do APK",
    analysis2: "Informações de esquema de assinatura e Hash",
    analysis3: "Tamanho e formato do APK",
    analysis4: "Permissões sensíveis e norma de segurança",

    signingTitle: "Assinatura e Verificação de APKs",
    signingDesc:
      "Assine suas aplicações com chaves JKS personalizadas ou verifique assinaturas de APKs existentes. Gere novas chaves e mantenha controle total sobre o processo de assinatura.",
    signing1: "Assinatura de APKs com chaves JKS",
    signing2: "Geração de novas chaves de assinatura",
    signing3: "Verificação de assinaturas existentes",
    signing4: "Alinhamento e otimização de APKs",

    logcatTitle: "Experiências Logcat",
    logcatDesc:
      "Acesse registros do logcat de forma intuitiva e eficiente. Visualize, filtre e exporte registros facilmente.",
    logcat1: "Visualização de registros do logcat",
    logcat2: "Filtragem de registros por níveis de log",
    logcat3: "Exportação de registros para arquivos",
    logcat4: "Salvar e exportar o registro",

    adbTitle: "Comandos ADB Avançados",
    adbDesc:
      "Execute comandos ADB complexos através de uma interface gráfica intuitiva. Automatize tarefas repetitivas e acesse funções avançadas sem memorizar comandos.",
    adb1: "Interface gráfica para comandos ADB",
    adb2: "Scripts predefinidos para tarefas comuns",
    adb3: "Execução de comandos personalizados",
    adb4: "Histórico de comandos executados",

    screenTitle: "Gravação e Captura de Tela",
    screenDesc:
      "Grave a tela do seu dispositivo Android e capture imagens em alta qualidade. Perfeito para criar tutoriais, documentar bugs ou compartilhar demonstrações.",
    screen1: "Gravação de tela em alta qualidade",
    screen2: "Capturas de tela instantâneas",
    screen3: "Configuração de resolução e fps",
    screen4: "Múltiplos formatos de exportação",

    managementTitle: "Configurações Globais",
    managementDesc:
      "Personalize sua experiência no ISV Toolkit. Altere o idioma, ajuste o tema visual e gerencie o status do seu terminal conectado remotamente.",
    management1: "Idiomas: Espanhol, Inglês e Português",
    management2: "Modo Escuro e Claro",
    management3: "Reboot remoto do terminal",
    management4: "Persistência de preferências",

    integrationSimTitle: "Simuladores de Integração",
    integrationSimDesc:
      "Suíte completa de simuladores projetada para integradores. Teste e valide a comunicação via simulador SDK, protocolo simplificado e conexão por portas COM.",
    integrationSim1: "Simulador SDK e ambiente de testes",
    integrationSim2: "Suporte para protocolo simplificado",
    integrationSim3: "Conexão e inspeção por portas COM (Serial/USB)",
    integrationSim4: "Validação de comunicação em tempo real para integradores",

    // Download Section
    downloadTitle: "Baixar ISV Toolkit",
    downloadSubtitle:
      "Disponível para Windows",
    windows: "Windows",
    version: "Versão:",
    file: "Arquivo:",
    size: "Tamanho:",
    requirements: "Requisitos:",
    downloadButton: "Baixar para",
    requirementsTitle: "Requisitos do Sistema",
    dependenciesTitle: "Dependências Necessárias",
    os: "Sistema Operacional",
    osDesc: "Windows 7/8/10/11 (64-bit)",
    ram: "Memória RAM",
    ramDesc: "Mínimo 4GB, recomendado 8GB",
    disk: "Espaço em Disco",
    diskDesc: "500MB mínimo, 1GB recomendado",
    internet: "Conexão com Internet",
    internetDesc: "Para baixar dependências e atualizações",
    platformTools: "Platform Tools",
    platformToolsDesc: "ADB e Fastboot essenciais",
    buildTools: "Build Tools",
    buildToolsDesc: "AAPT, APKSigner, etc.",
    jdk: "JDK 11",
    jdkDesc: "Para JarSigner",
    downloading: "Baixando...",
    learnMore: "Saiba mais",
  
    // Simulator
    simulatorTitle: "Simulador Cloud to Cloud",
    simulatorDesc: "Console de comandos C2C. Valide tokens e examine os logs de eventos.",
    backToMain: "Voltar ao início",
    simSendBtn: "Enviar Requisição",
    simEnv: "AMBIENTE",
    simCommand: "COMANDO",
    simParams: "PARÂMETROS",
    simHistory: "HISTÓRICO",
    simFullHistory: "Ver histórico completo",
    simTransactions: "transações",
    simTransaction: "transação",
    simShowing: "Mostrando",
    simOf: "de",
    simPerPage: "Por pág:",
    simSearchPlaceholder: "Pesquisar por endpoint, status (200, 400), método...",
    simNoHistory: "Sem histórico",
    confirmClearHistoryTitle: "Limpar Histórico",
    confirmClearHistoryHeading: "Limpar histórico de transações?",
    confirmClearHistoryDesc: "Esta ação excluirá permanentemente todas as transações salvas no armazenamento local. Isso não pode ser desfeito.",
    confirmClear: "Sim, limpar histórico",
    cancel: "Cancelar",
    simTriadWarn: "Faltam dados da tríade (ID Terminal, ID Sucursal ou Serial Number). Executar comando mesmo assim?",
    simTokenActive: "Bearer Token Ativo",
    simNoToken: "Sem Token — abrir configurações",
    simAuthBtn: "Gerar Auth Token",
    simClearBtn: "Limpar",
    simProdEnv: "PRODUÇÃO",
    simParamsCount: "parâmetros",
    simWaiting: "Aguardando requisição...",
    tokenSaved: "Token Salvo",
    unauthorizedTitle: "Acesso Negado (401)",
    unauthorizedDesc: "O Simulator recebeu um erro 401. O token pode estar expirado ou não configurado. Gerar um novo?",
    ignoreBtn: "Ignorar",
    tokenConfigTitle: "Configuração de Token",
    terminalCreds: "Credenciais do Terminal",
    tokenStatus: "Status do Token",
    tokenActive: "TOKEN ATIVO",
    tokenMissing: "SEM TOKEN",
    tokenInfo: "Será enviado como Authorization: Bearer em cada solicitação.",
    tokenGuide: "Insira suas credenciais e pressione o botão obter.",
    tokenConfigBtn: "Configuração de Token",
    clientIdLabel: "CLIENT ID",
    clientSecretLabel: "CLIENT SECRET",
    fetchTokenBtn: "Obter Token",
    fetchingToken: "Obtendo...",
    copy: "Copiar",
    copied: "Copiado!",
    
    // Commands
    "cmd.poll": "Conexão",
    "cmd.validate_ar": "Validar comunicação",
    "cmd.params_ar": "Informação de terminal",
    "cmd.sale_ar": "Venda",
    "cmd.return_ar": "Reembolso",
    "cmd.lastvoucher_ar": "Reimprimir",
    "cmd.details_ar": "Detalhes de Venda",
    "cmd.totals_ar": "Totais",
    "cmd.c2c_sale": "Venda",
    "cmd.sale_promo": "Venda Promo",
    "cmd.refund": "Anulação",
    "cmd.close": "Fechamento",
    "cmd.details": "Detalhes",
    "cmd.return": "Reembolso",
    "cmd.duplicate": "Duplicado",
    "cmd.bioauth": "Bio Auth",
    "cmd.print": "Imprimir",
    "cmd.c2c_mode": "Modo C2C",
    "cmd.flash_sale": "Venda Flash",

    // Fields
    "field.idTerminal": "ID Terminal",
    "field.idSucursal": "ID Sucursal",
    "field.serialNumber": "Serial Number",
    "field.amount": "Valor ($)",
    "field.ticketNumber": "Ticket #",
    "field.customId": "Custom ID",
    "field.idPromo": "ID Promo",
    "field.operationId": "N° de Comprovante",
    "field.authCode": "Cód. Autorização",
    "field.installments": "Parcelas",
    "field.printOnPos": "Imprimir no POS",
    "field.c2cMode": "Modo Atendido/Desatendido",
    "field.rutToValidate": "RUT para Validar",
    "field.authType": "Tipo Auth",
    "field.saleType": "Tipo de Venda",
    "field.paymentCategory": "Categoria de Pagamento",
    "paymentCategory.none": "Nenhuma",
    "field.employeeId": "ID do Empregado",
    "field.flashCount": "Quantidade de Vendas",
    "field.flashAltThreshold": "Mudar valor a partir da venda #",
    "field.flashBaseAmount": "Valor Base ($)",
    "field.flashAltAmount": "Valor Alternativo ($)",
    "field.amountStatic": "Valor Fijo",
    "field.ticketStatic": "Ticket Fijo",
    "triad.promptName": "Insira um nome para a tríade:",
    "triad.pasteTitle": "Colagem Especial de Tríade",
    "triad.pastePlaceholder": "Cole aqui os dados do terminal (separados por tabulação, vírgulas ou espaços)...",
    "triad.pasteApply": "Processar",
    "triad.pasteError": "Não foi possível detectar um formato de tríade válido. Certifique-se de incluir ID Terminal, ID Sucursal e Serial Number.",
    "triad.pasteSuccess": "Tríade carregada com sucesso",
    "viewFullHistory": "Ver transações restantes ({count})",
    simClearResponse: "Limpar Response",
    confirmClearToken: "Tem certeza de que deseja apagar o Token salvo?",
    simVersionNotice: "Este comando, assim como Venta Promo, c2cmode e Bio Auth, é apenas para iOnetech versão 1.0.X",
    confirmClearHistory: "Tem certeza de que deseja apagar o histórico de transações?",
    simAtendido: "Atendido",
    simDesatendido: "Desatendido",
    countryChile: "🇨🇱 Chile",
    countryArgentina: "🇦🇷 Argentina",
    simCountrySelectLabel: "SELECIONAR PAÍS",
    cancelConfirm: "A transação continuará no serviço, mas se você cancelar, não poderá ver a resposta nesta tela.",
    simCancelBtn: "Cancelar",
    simStatus: "Status",
    simRequestBody: "Corpo da Requisição",
    simResponseData: "Dados da Resposta",
    simTransactionDetail: "Detalhes da Transação",
    simCopied: "Copiado para a área de transferência",
    simSending: "Enviando...",
    simBackToCommands: "Voltar aos comandos",
    copyResponse: "Copiar Resposta",
    clearResponse: "Limpar Resposta",
    simTourTooltip: "Iniciar Tour Interativo",
    copyToken: "Copiar Token",
    copyRequest: "Copiar JSON",
    edit: "Editar",
    delete: "Excluir",
    simClearHistory: "Limpar Histórico",
    // Onboarding
    "tour.welcome": "Bem-vindo ao Simulador C2C! Aqui você pode testar e validar comandos sem a necessidade do Postman.",
    "tour.countrySelector": "Primeiro, escolha o País e o Ambiente (DEV, UAT, PROD) no qual deseja operar. Isso ajustará a URL da API automaticamente.",
    "tour.authBtn": "Configure suas credenciais e obtenha seu Token. É essencial para poder autorizar as transações.",
    "tour.requestResponse": "Aqui você verá o corpo da sua requisição (JSON) e a resposta exata do servidor.",
    "tour.sendBtn": "Assim que tudo estiver configurado, clique aqui para enviar o comando!",
    "tour.commandSelector": "Abra este menu para selecionar o tipo de operação: Venda, Anulação, Fechamento, etc.",
    "tour.triads": "Para evitar digitar sempre os mesmos dados, você pode salvar suas combinações frequentes de Terminal, Filial e Número de Série (Tríades).",
    "tour.params": "Atenção a estes campos! Aqui você definirá exatamente os parâmetros dinâmicos que enviará no corpo (body) da sua requisição ao POS (valor, número do ticket, etc).",
    "tour.history": "Todas as suas operações recentes serão registradas neste histórico para que você possa revisá-las detalhadamente.",
    // Triads
    "triad.requiredFields": "ID Terminal, ID Sucursal e Serial Number são obrigatórios",
    "triad.nameRequired": "Nome é obrigatório",
    "triad.terminalRequired": "ID Terminal é obrigatório",
    "triad.sucursalRequired": "ID Sucursal é obrigatório",
    "triad.serialRequired": "Serial Number é obrigatório",
    "triad.maxLength": "Os campos não devem exceder 20 caracteres",
    "triad.exists": "Tríade já existe. Selecionada.",
    "triad.created": "Tríade criada",
    "triad.confirmDelete": "Excluir tríade \"{name}\"?",
    "triad.duplicate": "A tríade modificada coincide com outra existente",
    "triad.saved": "Tríade salva",
    "triad.title": "Tríades Salvas",
    "triad.createBtn": "CRIAR TRÍADE",
    "triad.noTriads": "Não há tríades salvas",
    "triad.createTitle": "Criar Tríade",
    "triad.editTitle": "Editar Tríade",
    "triad.nameLabel": "Nome",
    "triad.cancelBtn": "Cancelar",
    "triad.createAction": "Criar",
    "triad.saveAction": "Salvar Triade",
    // Token Modal / Fetching
    "token.envDev": "DEV - Ambiente Desenvolvimento",
    "token.envUat": "UAT - Ambiente de Testes",
    "token.privacyNote": "Suas credenciais são processadas de forma segura e armazenadas apenas localmente.",
    "token.closeModal": "Fechar modal",
    simTokenRequired: "É necessário obter um token primeiro",
    errorInvalidAmount: "❌ Erro: O valor é inválido",
    errorTicketRequired: "❌ Erro: O número do ticket é obrigatório",
    requestCancelled: "🚫 Requisição cancelada",
    flashSaleStarting: "⚡ Iniciando modo Venda Flash...",
    flashSaleStopping: "⏹️ Parando Venda Flash...",
    envLabel: "Ambiente",
    templateLoaded: "Modelo carregado",
  },
};

// Crear el contexto
const LanguageContext = createContext();

// Proveedor del contexto
export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState("es");

  // Cargar idioma guardado
  useEffect(() => {
    const savedLanguage = localStorage.getItem("language");
    if (savedLanguage && translations[savedLanguage]) {
      setLanguage(savedLanguage);
    } else {
      // Detectar idioma del navegador
      const browserLang = navigator.language.slice(0, 2);
      if (translations[browserLang]) {
        setLanguage(browserLang);
      }
    }
  }, []);

  // Guardar idioma cuando cambia
  useEffect(() => {
    localStorage.setItem("language", language);
    document.documentElement.lang = language;
  }, [language]);

  // Función para cambiar idioma
  const changeLanguage = (lang) => {
    if (translations[lang]) {
      setLanguage(lang);
    }
  };

  // Función para obtener traducción
  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Hook personalizado para usar el contexto
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
